### PR TITLE
New York Times Article Look-alike

### PR DESCRIPTION
**Pull request by anewman15**
In this PR we re-created a NYT Space and Cosmos article.

It consists of:

-- A navbar at the top
-- An article header above the main article
-- The main article contains a section with details about the author and his social links, multiple sections containing the text of the article, an illustration where we used CSS Grid, a Youtube video, an image and links to comments area.
-- A recommended articles section
-- A bottom navigation area
-- A page footer section

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Comment by anewman15** [comment]
Thanks @christianotieno. We made the recommended changes.

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey  :wave: 
## Good attempts on this one :muscle: :+1: 

### This page is a clone page from the [NT](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0), therefore there are a few changes you have to fix in order to achieve it

## Here are the issues to address to get the project meet the requirement:wink:

## Tittles
- [ ] All titles should be aligned to the middle 
##### Example:
Screenshot from 2020-04-10 20-03-01
##### Yours: 
Screenshot from 2020-04-10 20-08-50

## Video and Images
- [ ] All of them need to be centered
##### Required:
Screenshot from 2020-04-10 20-04-52
##### Yours: 
Screenshot from 2020-04-10 20-01-48

## Edditors Pick
- [ ] Can't see images, please fix this issue. They are stretching 
##### Required:
Screenshot from 2020-04-10 20-04-33
##### Yours: 
Screenshot from 2020-04-10 20-02-25

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by anewman15** [comment]
Hi @Dandush03,

Could you kindly confirm the screenshots belong to our project? Because I suspect they don't look like they were taken from our one.

Here are the indications:
-- The images in the indicated editor's picks section are different from those we used in the same section in our project.
-- We didn't use word spacing in the Youtube video caption, as seen when you look closely in the Youtube video screenshot.
-- We exercised great care in placing the contents at the center using margin auto and everything seems to be centered when we examine in our end, even when we resize the viewport.

Our code seems ok when we run it in our browsers.

I hope to receive your confirmation and we will act accordingly.

Many thanks in advance.
Abdullah

**Comment by Dandush03** [comment]
## Hey guys :wave: 

# I'm sorry for the confusion, I will see it will get fix ASAP :muscle: 

### Best regards

**Comment by lekegitrepo** [comment]
### @anewman15 and @8Bts 👏 💯 🥇 
### This page looks great now. This project is approved.

### Reviewed by _Temitayo Adeleke_

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Pull request merged**
